/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AmenityResponse {
    'id'?: string;
    'name'?: string;
    'slug'?: string;
    'icon'?: string;
    'category'?: AmenityResponseCategoryEnum;
    'sortOrder'?: number;
}

export const AmenityResponseCategoryEnum = {
    Security: 'SECURITY',
    Furniture: 'FURNITURE',
    Utility: 'UTILITY',
    Bathroom: 'BATHROOM',
    Kitchen: 'KITCHEN',
} as const;

export type AmenityResponseCategoryEnum = typeof AmenityResponseCategoryEnum[keyof typeof AmenityResponseCategoryEnum];


