/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PushTokenResponse } from './push-token-response';

export interface ApiResponsePushTokenResponse {
    'success'?: boolean;
    'message'?: string;
    'data'?: PushTokenResponse;
    'timestamp'?: string;
}

