/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ConversationResponse {
    'id'?: string;
    'listingId'?: string;
    'clientId'?: string;
    'hostId'?: string;
    'lastMessageAt'?: string;
    'lastMessagePreview'?: string;
    'clientUnreadCount'?: number;
    'hostUnreadCount'?: number;
    'unreadCount'?: number;
    'createdAt'?: string;
    'updatedAt'?: string;
}

