/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ListingMediaDto } from './listing-media-dto';

export interface ListingDetailResponse {
    'id'?: string;
    'ownerId'?: string;
    'agentId'?: string;
    'title'?: string;
    'slug'?: string;
    'description'?: string;
    'address'?: string;
    'area'?: number;
    'bedrooms'?: number;
    'bathrooms'?: number;
    'floors'?: number;
    'status'?: ListingDetailResponseStatusEnum;
    'listingType'?: ListingDetailResponseListingTypeEnum;
    'propertyType'?: string;
    'province'?: string;
    'ward'?: string;
    'currentPrice'?: number;
    'listingMediaDtos'?: Array<ListingMediaDto>;
    'amenities'?: Array<string>;
}

export const ListingDetailResponseStatusEnum = {
    Approved: 'APPROVED',
    Pending: 'PENDING',
} as const;

export type ListingDetailResponseStatusEnum = typeof ListingDetailResponseStatusEnum[keyof typeof ListingDetailResponseStatusEnum];
export const ListingDetailResponseListingTypeEnum = {
    ForSale: 'FOR_SALE',
    ForRent: 'FOR_RENT',
} as const;

export type ListingDetailResponseListingTypeEnum = typeof ListingDetailResponseListingTypeEnum[keyof typeof ListingDetailResponseListingTypeEnum];


