/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ListingMediaDto } from './listing-media-dto';

export interface ListingSummaryResponse {
    'id'?: string;
    'ownerId'?: string;
    'agentId'?: string;
    'title'?: string;
    'slug'?: string;
    'description'?: string;
    'provinceName'?: string;
    'thumbnails'?: Array<ListingMediaDto>;
    'area'?: number;
    'listingType'?: ListingSummaryResponseListingTypeEnum;
    'amountVND'?: number;
}

export const ListingSummaryResponseListingTypeEnum = {
    ForSale: 'FOR_SALE',
    ForRent: 'FOR_RENT',
} as const;

export type ListingSummaryResponseListingTypeEnum = typeof ListingSummaryResponseListingTypeEnum[keyof typeof ListingSummaryResponseListingTypeEnum];


