/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MessageResponse {
    'id'?: string;
    'conversationId'?: string;
    'senderId'?: string;
    'content'?: string;
    'messageType'?: MessageResponseMessageTypeEnum;
    'attachmentUrl'?: string;
    'attachmentName'?: string;
    'attachmentSize'?: number;
    'attachmentMime'?: string;
    'readAt'?: string;
    'system'?: boolean;
    'createdAt'?: string;
}

export const MessageResponseMessageTypeEnum = {
    Text: 'TEXT',
    Image: 'IMAGE',
    File: 'FILE',
    System: 'SYSTEM',
} as const;

export type MessageResponseMessageTypeEnum = typeof MessageResponseMessageTypeEnum[keyof typeof MessageResponseMessageTypeEnum];


