/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ModerationListingSummaryResponse {
    'id'?: string;
    'title'?: string;
    'slug'?: string;
    'address'?: string;
    'area'?: number;
    'amountVND'?: number;
    'listingType'?: string;
    'propertyTypeName'?: string;
    'ownerId'?: string;
    'ownerName'?: string;
    'status'?: string;
    'createdAt'?: string;
}

