/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ListingSummaryResponse } from './listing-summary-response';
// May contain unused imports in some cases
// @ts-ignore
import type { PageableObject } from './pageable-object';
// May contain unused imports in some cases
// @ts-ignore
import type { SortObject } from './sort-object';

export interface PageListingSummaryResponse {
    'totalElements'?: number;
    'totalPages'?: number;
    'pageable'?: PageableObject;
    'first'?: boolean;
    'last'?: boolean;
    'size'?: number;
    'content'?: Array<ListingSummaryResponse>;
    'number'?: number;
    'sort'?: SortObject;
    'numberOfElements'?: number;
    'empty'?: boolean;
}

