/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PushTokenResponse {
    'id'?: string;
    'userId'?: string;
    'token'?: string;
    'platform'?: PushTokenResponsePlatformEnum;
    'deviceId'?: string;
    'active'?: boolean;
    'lastUsed'?: string;
    'createdAt'?: string;
}

export const PushTokenResponsePlatformEnum = {
    Fcm: 'FCM',
    Web: 'WEB',
} as const;

export type PushTokenResponsePlatformEnum = typeof PushTokenResponsePlatformEnum[keyof typeof PushTokenResponsePlatformEnum];


