/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ReviewResponse {
    'id'?: string;
    'listingId'?: string;
    'reviewerId'?: string;
    'scheduleId'?: string;
    'rating'?: number;
    'locationRating'?: number;
    'accuracyRating'?: number;
    'hostRating'?: number;
    'title'?: string;
    'comment'?: string;
    'verified'?: boolean;
    'hidden'?: boolean;
    'ownerReply'?: string;
    'ownerRepliedAt'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
}

