/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SendMessageRequest {
    'content'?: string;
    'messageType'?: SendMessageRequestMessageTypeEnum;
    'attachmentUrl'?: string;
    'attachmentName'?: string;
    'attachmentSize'?: number;
    'attachmentMime'?: string;
    'contentValid'?: boolean;
}

export const SendMessageRequestMessageTypeEnum = {
    Text: 'TEXT',
    Image: 'IMAGE',
    File: 'FILE',
    System: 'SYSTEM',
} as const;

export type SendMessageRequestMessageTypeEnum = typeof SendMessageRequestMessageTypeEnum[keyof typeof SendMessageRequestMessageTypeEnum];


