/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserProfileResponse {
    'id'?: string;
    'email'?: string;
    'fullName'?: string;
    'phone'?: string;
    'avatarUrl'?: string;
    'authProvider'?: UserProfileResponseAuthProviderEnum;
    'role'?: UserProfileResponseRoleEnum;
    'status'?: UserProfileResponseStatusEnum;
    'emailVerified'?: boolean;
    'bio'?: string;
    'createdAt'?: string;
}

export const UserProfileResponseAuthProviderEnum = {
    Local: 'LOCAL',
    Google: 'GOOGLE',
    Apple: 'APPLE',
    Facebook: 'FACEBOOK',
} as const;

export type UserProfileResponseAuthProviderEnum = typeof UserProfileResponseAuthProviderEnum[keyof typeof UserProfileResponseAuthProviderEnum];
export const UserProfileResponseRoleEnum = {
    Guest: 'GUEST',
    RegularUser: 'REGULAR_USER',
    Agent: 'AGENT',
    Admin: 'ADMIN',
} as const;

export type UserProfileResponseRoleEnum = typeof UserProfileResponseRoleEnum[keyof typeof UserProfileResponseRoleEnum];
export const UserProfileResponseStatusEnum = {
    Active: 'ACTIVE',
    Suspended: 'SUSPENDED',
    PendingVerify: 'PENDING_VERIFY',
} as const;

export type UserProfileResponseStatusEnum = typeof UserProfileResponseStatusEnum[keyof typeof UserProfileResponseStatusEnum];


