/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ViewingScheduleResponse {
    'id'?: string;
    'listingId'?: string;
    'clientId'?: string;
    'hostId'?: string;
    'scheduledLocalTime'?: string;
    'scheduledUtcTime'?: string;
    'scheduledEndUtcTime'?: string;
    'durationMins'?: number;
    'timezoneId'?: string;
    'status'?: string;
    'note'?: string;
    'cancelReason'?: string;
    'cancelledBy'?: string;
    'cancelledAt'?: string;
    'confirmedAt'?: string;
    'confirmationPromptedAt'?: string;
    'completedAt'?: string;
    'reminderSent'?: boolean;
    'version'?: number;
}

