/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListPropertyTypeResponse } from '../models';
// @ts-ignore
import type { ApiResponsePropertyTypeResponse } from '../models';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
// @ts-ignore
import type { UpdatePropertyTypeRequest } from '../models';
/**
 * AdminPropertyTypesApi - axios parameter creator
 */
export const AdminPropertyTypesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new property type
         * @summary Create property type
         * @param {UpdatePropertyTypeRequest} updatePropertyTypeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPropertyType: async (updatePropertyTypeRequest: UpdatePropertyTypeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updatePropertyTypeRequest' is not null or undefined
            assertParamExists('createPropertyType', 'updatePropertyTypeRequest', updatePropertyTypeRequest)
            const localVarPath = `/admin/property-types`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePropertyTypeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a property type by ID
         * @summary Delete property type
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePropertyType: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePropertyType', 'id', id)
            const localVarPath = `/admin/property-types/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves all property types ordered by sortOrder
         * @summary Get all property types
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllPropertyTypes: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/admin/property-types`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a specific property type by its ID
         * @summary Get property type by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPropertyTypeById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPropertyTypeById', 'id', id)
            const localVarPath = `/admin/property-types/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates an existing property type and publishes PropertyTypeUpdatedEvent
         * @summary Update property type
         * @param {number} id 
         * @param {UpdatePropertyTypeRequest} updatePropertyTypeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePropertyType: async (id: number, updatePropertyTypeRequest: UpdatePropertyTypeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePropertyType', 'id', id)
            // verify required parameter 'updatePropertyTypeRequest' is not null or undefined
            assertParamExists('updatePropertyType', 'updatePropertyTypeRequest', updatePropertyTypeRequest)
            const localVarPath = `/admin/property-types/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePropertyTypeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminPropertyTypesApi - functional programming interface
 */
export const AdminPropertyTypesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminPropertyTypesApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new property type
         * @summary Create property type
         * @param {UpdatePropertyTypeRequest} updatePropertyTypeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPropertyType(updatePropertyTypeRequest: UpdatePropertyTypeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePropertyTypeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPropertyType(updatePropertyTypeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPropertyTypesApi.createPropertyType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a property type by ID
         * @summary Delete property type
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePropertyType(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePropertyType(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPropertyTypesApi.deletePropertyType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves all property types ordered by sortOrder
         * @summary Get all property types
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllPropertyTypes(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListPropertyTypeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllPropertyTypes(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPropertyTypesApi.getAllPropertyTypes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves a specific property type by its ID
         * @summary Get property type by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPropertyTypeById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePropertyTypeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPropertyTypeById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPropertyTypesApi.getPropertyTypeById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates an existing property type and publishes PropertyTypeUpdatedEvent
         * @summary Update property type
         * @param {number} id 
         * @param {UpdatePropertyTypeRequest} updatePropertyTypeRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePropertyType(id: number, updatePropertyTypeRequest: UpdatePropertyTypeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePropertyTypeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePropertyType(id, updatePropertyTypeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminPropertyTypesApi.updatePropertyType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminPropertyTypesApi - factory interface
 */
export const AdminPropertyTypesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminPropertyTypesApiFp(configuration)
    return {
        /**
         * Creates a new property type
         * @summary Create property type
         * @param {AdminPropertyTypesApiCreatePropertyTypeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPropertyType(requestParameters: AdminPropertyTypesApiCreatePropertyTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePropertyTypeResponse> {
            return localVarFp.createPropertyType(requestParameters.updatePropertyTypeRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a property type by ID
         * @summary Delete property type
         * @param {AdminPropertyTypesApiDeletePropertyTypeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePropertyType(requestParameters: AdminPropertyTypesApiDeletePropertyTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.deletePropertyType(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves all property types ordered by sortOrder
         * @summary Get all property types
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllPropertyTypes(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListPropertyTypeResponse> {
            return localVarFp.getAllPropertyTypes(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a specific property type by its ID
         * @summary Get property type by ID
         * @param {AdminPropertyTypesApiGetPropertyTypeByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPropertyTypeById(requestParameters: AdminPropertyTypesApiGetPropertyTypeByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePropertyTypeResponse> {
            return localVarFp.getPropertyTypeById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates an existing property type and publishes PropertyTypeUpdatedEvent
         * @summary Update property type
         * @param {AdminPropertyTypesApiUpdatePropertyTypeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePropertyType(requestParameters: AdminPropertyTypesApiUpdatePropertyTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePropertyTypeResponse> {
            return localVarFp.updatePropertyType(requestParameters.id, requestParameters.updatePropertyTypeRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminPropertyTypesApi - interface
 */
export interface AdminPropertyTypesApiInterface {
    /**
     * Creates a new property type
     * @summary Create property type
     * @param {AdminPropertyTypesApiCreatePropertyTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createPropertyType(requestParameters: AdminPropertyTypesApiCreatePropertyTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePropertyTypeResponse>;

    /**
     * Deletes a property type by ID
     * @summary Delete property type
     * @param {AdminPropertyTypesApiDeletePropertyTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deletePropertyType(requestParameters: AdminPropertyTypesApiDeletePropertyTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid>;

    /**
     * Retrieves all property types ordered by sortOrder
     * @summary Get all property types
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllPropertyTypes(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListPropertyTypeResponse>;

    /**
     * Retrieves a specific property type by its ID
     * @summary Get property type by ID
     * @param {AdminPropertyTypesApiGetPropertyTypeByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPropertyTypeById(requestParameters: AdminPropertyTypesApiGetPropertyTypeByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePropertyTypeResponse>;

    /**
     * Updates an existing property type and publishes PropertyTypeUpdatedEvent
     * @summary Update property type
     * @param {AdminPropertyTypesApiUpdatePropertyTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updatePropertyType(requestParameters: AdminPropertyTypesApiUpdatePropertyTypeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePropertyTypeResponse>;

}

/**
 * Request parameters for createPropertyType operation in AdminPropertyTypesApi.
 */
export interface AdminPropertyTypesApiCreatePropertyTypeRequest {
    readonly updatePropertyTypeRequest: UpdatePropertyTypeRequest
}

/**
 * Request parameters for deletePropertyType operation in AdminPropertyTypesApi.
 */
export interface AdminPropertyTypesApiDeletePropertyTypeRequest {
    readonly id: number
}

/**
 * Request parameters for getPropertyTypeById operation in AdminPropertyTypesApi.
 */
export interface AdminPropertyTypesApiGetPropertyTypeByIdRequest {
    readonly id: number
}

/**
 * Request parameters for updatePropertyType operation in AdminPropertyTypesApi.
 */
export interface AdminPropertyTypesApiUpdatePropertyTypeRequest {
    readonly id: number

    readonly updatePropertyTypeRequest: UpdatePropertyTypeRequest
}

/**
 * AdminPropertyTypesApi - object-oriented interface
 */
export class AdminPropertyTypesApi extends BaseAPI implements AdminPropertyTypesApiInterface {
    /**
     * Creates a new property type
     * @summary Create property type
     * @param {AdminPropertyTypesApiCreatePropertyTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createPropertyType(requestParameters: AdminPropertyTypesApiCreatePropertyTypeRequest, options?: RawAxiosRequestConfig) {
        return AdminPropertyTypesApiFp(this.configuration).createPropertyType(requestParameters.updatePropertyTypeRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes a property type by ID
     * @summary Delete property type
     * @param {AdminPropertyTypesApiDeletePropertyTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePropertyType(requestParameters: AdminPropertyTypesApiDeletePropertyTypeRequest, options?: RawAxiosRequestConfig) {
        return AdminPropertyTypesApiFp(this.configuration).deletePropertyType(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves all property types ordered by sortOrder
     * @summary Get all property types
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllPropertyTypes(options?: RawAxiosRequestConfig) {
        return AdminPropertyTypesApiFp(this.configuration).getAllPropertyTypes(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a specific property type by its ID
     * @summary Get property type by ID
     * @param {AdminPropertyTypesApiGetPropertyTypeByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPropertyTypeById(requestParameters: AdminPropertyTypesApiGetPropertyTypeByIdRequest, options?: RawAxiosRequestConfig) {
        return AdminPropertyTypesApiFp(this.configuration).getPropertyTypeById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates an existing property type and publishes PropertyTypeUpdatedEvent
     * @summary Update property type
     * @param {AdminPropertyTypesApiUpdatePropertyTypeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updatePropertyType(requestParameters: AdminPropertyTypesApiUpdatePropertyTypeRequest, options?: RawAxiosRequestConfig) {
        return AdminPropertyTypesApiFp(this.configuration).updatePropertyType(requestParameters.id, requestParameters.updatePropertyTypeRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

