/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseGdprPurgeResponse } from '../models';
// @ts-ignore
import type { ApiResponseListListingAuditHistoryResponse } from '../models';
// @ts-ignore
import type { ApiResponseListingStatusResponse } from '../models';
// @ts-ignore
import type { ApiResponsePageAuditLogResponse } from '../models';
// @ts-ignore
import type { ApiResponsePageModerationListingSummaryResponse } from '../models';
// @ts-ignore
import type { ApiResponsePageReportResponse } from '../models';
// @ts-ignore
import type { ApiResponseReportResponse } from '../models';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
// @ts-ignore
import type { Pageable } from '../models';
// @ts-ignore
import type { ResolveReportRequest } from '../models';
// @ts-ignore
import type { SuspendListingRequest } from '../models';
/**
 * AdminModerationApi - axios parameter creator
 */
export const AdminModerationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
         * @summary Get listing audit history
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingAuditHistory: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getListingAuditHistory', 'id', id)
            const localVarPath = `/admin/moderation/listings/{id}/audit`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
         * @summary Get listing audit history
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingAuditHistory1: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getListingAuditHistory1', 'id', id)
            const localVarPath = `/admin/moderation/listings/{id}/audit-history`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lightweight status endpoint for frontend polling following suspension requests
         * @summary Get listing status for polling
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingStatus: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getListingStatus', 'id', id)
            const localVarPath = `/admin/moderation/listings/{id}/status`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves paginated listings with PENDING status for admin moderation
         * @summary Get pending listings
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPendingListings: async (pageable: Pageable, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getPendingListings', 'pageable', pageable)
            const localVarPath = `/admin/moderation/listings/pending`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves paginated user reports filtered by status (default PENDING)
         * @summary Get user reports
         * @param {Pageable} pageable 
         * @param {GetReportsStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReports: async (pageable: Pageable, status?: GetReportsStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getReports', 'pageable', pageable)
            const localVarPath = `/admin/moderation/reports`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves paginated system audit logs with optional actorId and entity filters
         * @summary Get system audit logs
         * @param {Pageable} pageable 
         * @param {string} [actorId] 
         * @param {string} [entityType] 
         * @param {string} [entityId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSystemAuditLogs: async (pageable: Pageable, actorId?: string, entityType?: string, entityId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getSystemAuditLogs', 'pageable', pageable)
            const localVarPath = `/admin/moderation/audit-logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (actorId !== undefined) {
                localVarQueryParameter['actorId'] = actorId;
            }

            if (entityType !== undefined) {
                localVarQueryParameter['entityType'] = entityType;
            }

            if (entityId !== undefined) {
                localVarQueryParameter['entityId'] = entityId;
            }

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Executes Native SQL queries to scrub PII from both users and Envers users_aud tables for a soft-deleted user.
         * @summary Purge user PII under GDPR (Right to be Forgotten)
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purgeUserGdpr: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('purgeUserGdpr', 'userId', userId)
            const localVarPath = `/admin/moderation/users/{userId}/gdpr-purge`
                .replace('{userId}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Marks a report as RESOLVED or DISMISSED. If resolution=RESOLVED and suspendListing=true, directly sets the listing status to SUSPENDED within the same transaction and publishes a ListingSuspendedEvent after commit to notify the listing owner.
         * @summary Resolve a user report
         * @param {string} id 
         * @param {ResolveReportRequest} resolveReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resolveReport: async (id: string, resolveReportRequest: ResolveReportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('resolveReport', 'id', id)
            // verify required parameter 'resolveReportRequest' is not null or undefined
            assertParamExists('resolveReport', 'resolveReportRequest', resolveReportRequest)
            const localVarPath = `/admin/moderation/reports/{id}/resolve`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(resolveReportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Directly suspends the listing within the current transaction, publishes a ListingSuspendedEvent after commit to notify the listing owner, and returns 202 ACCEPTED.
         * @summary Suspend a listing
         * @param {string} id 
         * @param {SuspendListingRequest} suspendListingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        suspendListing: async (id: string, suspendListingRequest: SuspendListingRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('suspendListing', 'id', id)
            // verify required parameter 'suspendListingRequest' is not null or undefined
            assertParamExists('suspendListing', 'suspendListingRequest', suspendListingRequest)
            const localVarPath = `/admin/moderation/listings/{id}/suspend`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(suspendListingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminModerationApi - functional programming interface
 */
export const AdminModerationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminModerationApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
         * @summary Get listing audit history
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListingAuditHistory(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListListingAuditHistoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getListingAuditHistory(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminModerationApi.getListingAuditHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
         * @summary Get listing audit history
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListingAuditHistory1(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListListingAuditHistoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getListingAuditHistory1(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminModerationApi.getListingAuditHistory1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lightweight status endpoint for frontend polling following suspension requests
         * @summary Get listing status for polling
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListingStatus(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListingStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getListingStatus(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminModerationApi.getListingStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves paginated listings with PENDING status for admin moderation
         * @summary Get pending listings
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPendingListings(pageable: Pageable, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageModerationListingSummaryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPendingListings(pageable, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminModerationApi.getPendingListings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves paginated user reports filtered by status (default PENDING)
         * @summary Get user reports
         * @param {Pageable} pageable 
         * @param {GetReportsStatusEnum} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReports(pageable: Pageable, status?: GetReportsStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageReportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReports(pageable, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminModerationApi.getReports']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves paginated system audit logs with optional actorId and entity filters
         * @summary Get system audit logs
         * @param {Pageable} pageable 
         * @param {string} [actorId] 
         * @param {string} [entityType] 
         * @param {string} [entityId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSystemAuditLogs(pageable: Pageable, actorId?: string, entityType?: string, entityId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageAuditLogResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSystemAuditLogs(pageable, actorId, entityType, entityId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminModerationApi.getSystemAuditLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Executes Native SQL queries to scrub PII from both users and Envers users_aud tables for a soft-deleted user.
         * @summary Purge user PII under GDPR (Right to be Forgotten)
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async purgeUserGdpr(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseGdprPurgeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.purgeUserGdpr(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminModerationApi.purgeUserGdpr']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Marks a report as RESOLVED or DISMISSED. If resolution=RESOLVED and suspendListing=true, directly sets the listing status to SUSPENDED within the same transaction and publishes a ListingSuspendedEvent after commit to notify the listing owner.
         * @summary Resolve a user report
         * @param {string} id 
         * @param {ResolveReportRequest} resolveReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resolveReport(id: string, resolveReportRequest: ResolveReportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseReportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resolveReport(id, resolveReportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminModerationApi.resolveReport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Directly suspends the listing within the current transaction, publishes a ListingSuspendedEvent after commit to notify the listing owner, and returns 202 ACCEPTED.
         * @summary Suspend a listing
         * @param {string} id 
         * @param {SuspendListingRequest} suspendListingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async suspendListing(id: string, suspendListingRequest: SuspendListingRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.suspendListing(id, suspendListingRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminModerationApi.suspendListing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminModerationApi - factory interface
 */
export const AdminModerationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminModerationApiFp(configuration)
    return {
        /**
         * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
         * @summary Get listing audit history
         * @param {AdminModerationApiGetListingAuditHistoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingAuditHistory(requestParameters: AdminModerationApiGetListingAuditHistoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListListingAuditHistoryResponse> {
            return localVarFp.getListingAuditHistory(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
         * @summary Get listing audit history
         * @param {AdminModerationApiGetListingAuditHistory1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingAuditHistory1(requestParameters: AdminModerationApiGetListingAuditHistory1Request, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListListingAuditHistoryResponse> {
            return localVarFp.getListingAuditHistory1(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Lightweight status endpoint for frontend polling following suspension requests
         * @summary Get listing status for polling
         * @param {AdminModerationApiGetListingStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingStatus(requestParameters: AdminModerationApiGetListingStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListingStatusResponse> {
            return localVarFp.getListingStatus(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves paginated listings with PENDING status for admin moderation
         * @summary Get pending listings
         * @param {AdminModerationApiGetPendingListingsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPendingListings(requestParameters: AdminModerationApiGetPendingListingsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageModerationListingSummaryResponse> {
            return localVarFp.getPendingListings(requestParameters.pageable, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves paginated user reports filtered by status (default PENDING)
         * @summary Get user reports
         * @param {AdminModerationApiGetReportsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReports(requestParameters: AdminModerationApiGetReportsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageReportResponse> {
            return localVarFp.getReports(requestParameters.pageable, requestParameters.status, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves paginated system audit logs with optional actorId and entity filters
         * @summary Get system audit logs
         * @param {AdminModerationApiGetSystemAuditLogsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSystemAuditLogs(requestParameters: AdminModerationApiGetSystemAuditLogsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageAuditLogResponse> {
            return localVarFp.getSystemAuditLogs(requestParameters.pageable, requestParameters.actorId, requestParameters.entityType, requestParameters.entityId, options).then((request) => request(axios, basePath));
        },
        /**
         * Executes Native SQL queries to scrub PII from both users and Envers users_aud tables for a soft-deleted user.
         * @summary Purge user PII under GDPR (Right to be Forgotten)
         * @param {AdminModerationApiPurgeUserGdprRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purgeUserGdpr(requestParameters: AdminModerationApiPurgeUserGdprRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseGdprPurgeResponse> {
            return localVarFp.purgeUserGdpr(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Marks a report as RESOLVED or DISMISSED. If resolution=RESOLVED and suspendListing=true, directly sets the listing status to SUSPENDED within the same transaction and publishes a ListingSuspendedEvent after commit to notify the listing owner.
         * @summary Resolve a user report
         * @param {AdminModerationApiResolveReportRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resolveReport(requestParameters: AdminModerationApiResolveReportRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseReportResponse> {
            return localVarFp.resolveReport(requestParameters.id, requestParameters.resolveReportRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Directly suspends the listing within the current transaction, publishes a ListingSuspendedEvent after commit to notify the listing owner, and returns 202 ACCEPTED.
         * @summary Suspend a listing
         * @param {AdminModerationApiSuspendListingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        suspendListing(requestParameters: AdminModerationApiSuspendListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.suspendListing(requestParameters.id, requestParameters.suspendListingRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminModerationApi - interface
 */
export interface AdminModerationApiInterface {
    /**
     * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
     * @summary Get listing audit history
     * @param {AdminModerationApiGetListingAuditHistoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getListingAuditHistory(requestParameters: AdminModerationApiGetListingAuditHistoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListListingAuditHistoryResponse>;

    /**
     * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
     * @summary Get listing audit history
     * @param {AdminModerationApiGetListingAuditHistory1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getListingAuditHistory1(requestParameters: AdminModerationApiGetListingAuditHistory1Request, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListListingAuditHistoryResponse>;

    /**
     * Lightweight status endpoint for frontend polling following suspension requests
     * @summary Get listing status for polling
     * @param {AdminModerationApiGetListingStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getListingStatus(requestParameters: AdminModerationApiGetListingStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListingStatusResponse>;

    /**
     * Retrieves paginated listings with PENDING status for admin moderation
     * @summary Get pending listings
     * @param {AdminModerationApiGetPendingListingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPendingListings(requestParameters: AdminModerationApiGetPendingListingsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageModerationListingSummaryResponse>;

    /**
     * Retrieves paginated user reports filtered by status (default PENDING)
     * @summary Get user reports
     * @param {AdminModerationApiGetReportsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getReports(requestParameters: AdminModerationApiGetReportsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageReportResponse>;

    /**
     * Retrieves paginated system audit logs with optional actorId and entity filters
     * @summary Get system audit logs
     * @param {AdminModerationApiGetSystemAuditLogsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSystemAuditLogs(requestParameters: AdminModerationApiGetSystemAuditLogsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageAuditLogResponse>;

    /**
     * Executes Native SQL queries to scrub PII from both users and Envers users_aud tables for a soft-deleted user.
     * @summary Purge user PII under GDPR (Right to be Forgotten)
     * @param {AdminModerationApiPurgeUserGdprRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    purgeUserGdpr(requestParameters: AdminModerationApiPurgeUserGdprRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseGdprPurgeResponse>;

    /**
     * Marks a report as RESOLVED or DISMISSED. If resolution=RESOLVED and suspendListing=true, directly sets the listing status to SUSPENDED within the same transaction and publishes a ListingSuspendedEvent after commit to notify the listing owner.
     * @summary Resolve a user report
     * @param {AdminModerationApiResolveReportRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    resolveReport(requestParameters: AdminModerationApiResolveReportRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseReportResponse>;

    /**
     * Directly suspends the listing within the current transaction, publishes a ListingSuspendedEvent after commit to notify the listing owner, and returns 202 ACCEPTED.
     * @summary Suspend a listing
     * @param {AdminModerationApiSuspendListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    suspendListing(requestParameters: AdminModerationApiSuspendListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid>;

}

/**
 * Request parameters for getListingAuditHistory operation in AdminModerationApi.
 */
export interface AdminModerationApiGetListingAuditHistoryRequest {
    readonly id: string
}

/**
 * Request parameters for getListingAuditHistory1 operation in AdminModerationApi.
 */
export interface AdminModerationApiGetListingAuditHistory1Request {
    readonly id: string
}

/**
 * Request parameters for getListingStatus operation in AdminModerationApi.
 */
export interface AdminModerationApiGetListingStatusRequest {
    readonly id: string
}

/**
 * Request parameters for getPendingListings operation in AdminModerationApi.
 */
export interface AdminModerationApiGetPendingListingsRequest {
    readonly pageable: Pageable
}

/**
 * Request parameters for getReports operation in AdminModerationApi.
 */
export interface AdminModerationApiGetReportsRequest {
    readonly pageable: Pageable

    readonly status?: GetReportsStatusEnum
}

/**
 * Request parameters for getSystemAuditLogs operation in AdminModerationApi.
 */
export interface AdminModerationApiGetSystemAuditLogsRequest {
    readonly pageable: Pageable

    readonly actorId?: string

    readonly entityType?: string

    readonly entityId?: string
}

/**
 * Request parameters for purgeUserGdpr operation in AdminModerationApi.
 */
export interface AdminModerationApiPurgeUserGdprRequest {
    readonly userId: string
}

/**
 * Request parameters for resolveReport operation in AdminModerationApi.
 */
export interface AdminModerationApiResolveReportRequest {
    readonly id: string

    readonly resolveReportRequest: ResolveReportRequest
}

/**
 * Request parameters for suspendListing operation in AdminModerationApi.
 */
export interface AdminModerationApiSuspendListingRequest {
    readonly id: string

    readonly suspendListingRequest: SuspendListingRequest
}

/**
 * AdminModerationApi - object-oriented interface
 */
export class AdminModerationApi extends BaseAPI implements AdminModerationApiInterface {
    /**
     * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
     * @summary Get listing audit history
     * @param {AdminModerationApiGetListingAuditHistoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getListingAuditHistory(requestParameters: AdminModerationApiGetListingAuditHistoryRequest, options?: RawAxiosRequestConfig) {
        return AdminModerationApiFp(this.configuration).getListingAuditHistory(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves Envers revision history for a specific listing. Accessible via both /audit and /audit-history paths.
     * @summary Get listing audit history
     * @param {AdminModerationApiGetListingAuditHistory1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getListingAuditHistory1(requestParameters: AdminModerationApiGetListingAuditHistory1Request, options?: RawAxiosRequestConfig) {
        return AdminModerationApiFp(this.configuration).getListingAuditHistory1(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lightweight status endpoint for frontend polling following suspension requests
     * @summary Get listing status for polling
     * @param {AdminModerationApiGetListingStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getListingStatus(requestParameters: AdminModerationApiGetListingStatusRequest, options?: RawAxiosRequestConfig) {
        return AdminModerationApiFp(this.configuration).getListingStatus(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves paginated listings with PENDING status for admin moderation
     * @summary Get pending listings
     * @param {AdminModerationApiGetPendingListingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPendingListings(requestParameters: AdminModerationApiGetPendingListingsRequest, options?: RawAxiosRequestConfig) {
        return AdminModerationApiFp(this.configuration).getPendingListings(requestParameters.pageable, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves paginated user reports filtered by status (default PENDING)
     * @summary Get user reports
     * @param {AdminModerationApiGetReportsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getReports(requestParameters: AdminModerationApiGetReportsRequest, options?: RawAxiosRequestConfig) {
        return AdminModerationApiFp(this.configuration).getReports(requestParameters.pageable, requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves paginated system audit logs with optional actorId and entity filters
     * @summary Get system audit logs
     * @param {AdminModerationApiGetSystemAuditLogsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSystemAuditLogs(requestParameters: AdminModerationApiGetSystemAuditLogsRequest, options?: RawAxiosRequestConfig) {
        return AdminModerationApiFp(this.configuration).getSystemAuditLogs(requestParameters.pageable, requestParameters.actorId, requestParameters.entityType, requestParameters.entityId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Executes Native SQL queries to scrub PII from both users and Envers users_aud tables for a soft-deleted user.
     * @summary Purge user PII under GDPR (Right to be Forgotten)
     * @param {AdminModerationApiPurgeUserGdprRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public purgeUserGdpr(requestParameters: AdminModerationApiPurgeUserGdprRequest, options?: RawAxiosRequestConfig) {
        return AdminModerationApiFp(this.configuration).purgeUserGdpr(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Marks a report as RESOLVED or DISMISSED. If resolution=RESOLVED and suspendListing=true, directly sets the listing status to SUSPENDED within the same transaction and publishes a ListingSuspendedEvent after commit to notify the listing owner.
     * @summary Resolve a user report
     * @param {AdminModerationApiResolveReportRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public resolveReport(requestParameters: AdminModerationApiResolveReportRequest, options?: RawAxiosRequestConfig) {
        return AdminModerationApiFp(this.configuration).resolveReport(requestParameters.id, requestParameters.resolveReportRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Directly suspends the listing within the current transaction, publishes a ListingSuspendedEvent after commit to notify the listing owner, and returns 202 ACCEPTED.
     * @summary Suspend a listing
     * @param {AdminModerationApiSuspendListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public suspendListing(requestParameters: AdminModerationApiSuspendListingRequest, options?: RawAxiosRequestConfig) {
        return AdminModerationApiFp(this.configuration).suspendListing(requestParameters.id, requestParameters.suspendListingRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetReportsStatusEnum = {
    Pending: 'PENDING',
    UnderReview: 'UNDER_REVIEW',
    Resolved: 'RESOLVED',
    Dismissed: 'DISMISSED',
} as const;
export type GetReportsStatusEnum = typeof GetReportsStatusEnum[keyof typeof GetReportsStatusEnum];
