/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddFavoriteRequest } from '../models';
// @ts-ignore
import type { ApiResponseFavoriteResponse } from '../models';
// @ts-ignore
import type { ApiResponsePageFavoriteResponse } from '../models';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
// @ts-ignore
import type { Pageable } from '../models';
/**
 * FavoritesApi - axios parameter creator
 */
export const FavoritesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Thêm tin đăng vào yêu thích
         * @param {AddFavoriteRequest} addFavoriteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addFavorite: async (addFavoriteRequest: AddFavoriteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addFavoriteRequest' is not null or undefined
            assertParamExists('addFavorite', 'addFavoriteRequest', addFavoriteRequest)
            const localVarPath = `/favorites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addFavoriteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lấy danh sách yêu thích của user hiện tại
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyFavorites: async (pageable: Pageable, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getMyFavorites', 'pageable', pageable)
            const localVarPath = `/favorites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Xóa tin đăng khỏi yêu thích
         * @param {string} listingId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeFavorite: async (listingId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listingId' is not null or undefined
            assertParamExists('removeFavorite', 'listingId', listingId)
            const localVarPath = `/favorites/{listingId}`
                .replace('{listingId}', encodeURIComponent(String(listingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FavoritesApi - functional programming interface
 */
export const FavoritesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FavoritesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Thêm tin đăng vào yêu thích
         * @param {AddFavoriteRequest} addFavoriteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addFavorite(addFavoriteRequest: AddFavoriteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseFavoriteResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addFavorite(addFavoriteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FavoritesApi.addFavorite']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Lấy danh sách yêu thích của user hiện tại
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyFavorites(pageable: Pageable, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageFavoriteResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyFavorites(pageable, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FavoritesApi.getMyFavorites']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Xóa tin đăng khỏi yêu thích
         * @param {string} listingId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeFavorite(listingId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeFavorite(listingId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FavoritesApi.removeFavorite']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FavoritesApi - factory interface
 */
export const FavoritesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FavoritesApiFp(configuration)
    return {
        /**
         * 
         * @summary Thêm tin đăng vào yêu thích
         * @param {FavoritesApiAddFavoriteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addFavorite(requestParameters: FavoritesApiAddFavoriteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseFavoriteResponse> {
            return localVarFp.addFavorite(requestParameters.addFavoriteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lấy danh sách yêu thích của user hiện tại
         * @param {FavoritesApiGetMyFavoritesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyFavorites(requestParameters: FavoritesApiGetMyFavoritesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageFavoriteResponse> {
            return localVarFp.getMyFavorites(requestParameters.pageable, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Xóa tin đăng khỏi yêu thích
         * @param {FavoritesApiRemoveFavoriteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeFavorite(requestParameters: FavoritesApiRemoveFavoriteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.removeFavorite(requestParameters.listingId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FavoritesApi - interface
 */
export interface FavoritesApiInterface {
    /**
     * 
     * @summary Thêm tin đăng vào yêu thích
     * @param {FavoritesApiAddFavoriteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addFavorite(requestParameters: FavoritesApiAddFavoriteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseFavoriteResponse>;

    /**
     * 
     * @summary Lấy danh sách yêu thích của user hiện tại
     * @param {FavoritesApiGetMyFavoritesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMyFavorites(requestParameters: FavoritesApiGetMyFavoritesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageFavoriteResponse>;

    /**
     * 
     * @summary Xóa tin đăng khỏi yêu thích
     * @param {FavoritesApiRemoveFavoriteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeFavorite(requestParameters: FavoritesApiRemoveFavoriteRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid>;

}

/**
 * Request parameters for addFavorite operation in FavoritesApi.
 */
export interface FavoritesApiAddFavoriteRequest {
    readonly addFavoriteRequest: AddFavoriteRequest
}

/**
 * Request parameters for getMyFavorites operation in FavoritesApi.
 */
export interface FavoritesApiGetMyFavoritesRequest {
    readonly pageable: Pageable
}

/**
 * Request parameters for removeFavorite operation in FavoritesApi.
 */
export interface FavoritesApiRemoveFavoriteRequest {
    readonly listingId: string
}

/**
 * FavoritesApi - object-oriented interface
 */
export class FavoritesApi extends BaseAPI implements FavoritesApiInterface {
    /**
     * 
     * @summary Thêm tin đăng vào yêu thích
     * @param {FavoritesApiAddFavoriteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addFavorite(requestParameters: FavoritesApiAddFavoriteRequest, options?: RawAxiosRequestConfig) {
        return FavoritesApiFp(this.configuration).addFavorite(requestParameters.addFavoriteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Lấy danh sách yêu thích của user hiện tại
     * @param {FavoritesApiGetMyFavoritesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyFavorites(requestParameters: FavoritesApiGetMyFavoritesRequest, options?: RawAxiosRequestConfig) {
        return FavoritesApiFp(this.configuration).getMyFavorites(requestParameters.pageable, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Xóa tin đăng khỏi yêu thích
     * @param {FavoritesApiRemoveFavoriteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeFavorite(requestParameters: FavoritesApiRemoveFavoriteRequest, options?: RawAxiosRequestConfig) {
        return FavoritesApiFp(this.configuration).removeFavorite(requestParameters.listingId, options).then((request) => request(this.axios, this.basePath));
    }
}

