/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseListingDetailResponse } from '../models';
// @ts-ignore
import type { ApiResponsePageListingSummaryResponse } from '../models';
// @ts-ignore
import type { ApiResponseString } from '../models';
// @ts-ignore
import type { ListingUpsertRequest } from '../models';
/**
 * ListingControllerApi - axios parameter creator
 */
export const ListingControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ListingUpsertRequest} listingUpsertRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createListing: async (listingUpsertRequest: ListingUpsertRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listingUpsertRequest' is not null or undefined
            assertParamExists('createListing', 'listingUpsertRequest', listingUpsertRequest)
            const localVarPath = `/listing`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listingUpsertRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteListing: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteListing', 'id', id)
            const localVarPath = `/listing/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingDetail: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getListingDetail', 'id', id)
            const localVarPath = `/listing/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {GetListingsListingTypeEnum} listingType 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {number} [minPrice] 
         * @param {number} [maxPrice] 
         * @param {number} [minBedrooms] 
         * @param {number} [maxBedrooms] 
         * @param {number} [minBathrooms] 
         * @param {number} [maxBathrooms] 
         * @param {number} [minArea] 
         * @param {number} [maxArea] 
         * @param {string} [title] 
         * @param {string} [provinceCode] 
         * @param {string} [wardCode] 
         * @param {Array<number>} [amenityIds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListings: async (listingType: GetListingsListingTypeEnum, page?: number, size?: number, sort?: Array<string>, minPrice?: number, maxPrice?: number, minBedrooms?: number, maxBedrooms?: number, minBathrooms?: number, maxBathrooms?: number, minArea?: number, maxArea?: number, title?: string, provinceCode?: string, wardCode?: string, amenityIds?: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listingType' is not null or undefined
            assertParamExists('getListings', 'listingType', listingType)
            const localVarPath = `/listing`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            if (listingType !== undefined) {
                localVarQueryParameter['listingType'] = listingType;
            }

            if (minPrice !== undefined) {
                localVarQueryParameter['minPrice'] = minPrice;
            }

            if (maxPrice !== undefined) {
                localVarQueryParameter['maxPrice'] = maxPrice;
            }

            if (minBedrooms !== undefined) {
                localVarQueryParameter['minBedrooms'] = minBedrooms;
            }

            if (maxBedrooms !== undefined) {
                localVarQueryParameter['maxBedrooms'] = maxBedrooms;
            }

            if (minBathrooms !== undefined) {
                localVarQueryParameter['minBathrooms'] = minBathrooms;
            }

            if (maxBathrooms !== undefined) {
                localVarQueryParameter['maxBathrooms'] = maxBathrooms;
            }

            if (minArea !== undefined) {
                localVarQueryParameter['minArea'] = minArea;
            }

            if (maxArea !== undefined) {
                localVarQueryParameter['maxArea'] = maxArea;
            }

            if (title !== undefined) {
                localVarQueryParameter['title'] = title;
            }

            if (provinceCode !== undefined) {
                localVarQueryParameter['provinceCode'] = provinceCode;
            }

            if (wardCode !== undefined) {
                localVarQueryParameter['wardCode'] = wardCode;
            }

            if (amenityIds) {
                localVarQueryParameter['amenityIds'] = amenityIds;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {ListingUpsertRequest} listingUpsertRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateListing: async (id: string, listingUpsertRequest: ListingUpsertRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateListing', 'id', id)
            // verify required parameter 'listingUpsertRequest' is not null or undefined
            assertParamExists('updateListing', 'listingUpsertRequest', listingUpsertRequest)
            const localVarPath = `/listing/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(listingUpsertRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ListingControllerApi - functional programming interface
 */
export const ListingControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ListingControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {ListingUpsertRequest} listingUpsertRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createListing(listingUpsertRequest: ListingUpsertRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createListing(listingUpsertRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingControllerApi.createListing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteListing(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteListing(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingControllerApi.deleteListing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListingDetail(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListingDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getListingDetail(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingControllerApi.getListingDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {GetListingsListingTypeEnum} listingType 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {number} [minPrice] 
         * @param {number} [maxPrice] 
         * @param {number} [minBedrooms] 
         * @param {number} [maxBedrooms] 
         * @param {number} [minBathrooms] 
         * @param {number} [maxBathrooms] 
         * @param {number} [minArea] 
         * @param {number} [maxArea] 
         * @param {string} [title] 
         * @param {string} [provinceCode] 
         * @param {string} [wardCode] 
         * @param {Array<number>} [amenityIds] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListings(listingType: GetListingsListingTypeEnum, page?: number, size?: number, sort?: Array<string>, minPrice?: number, maxPrice?: number, minBedrooms?: number, maxBedrooms?: number, minBathrooms?: number, maxBathrooms?: number, minArea?: number, maxArea?: number, title?: string, provinceCode?: string, wardCode?: string, amenityIds?: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageListingSummaryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getListings(listingType, page, size, sort, minPrice, maxPrice, minBedrooms, maxBedrooms, minBathrooms, maxBathrooms, minArea, maxArea, title, provinceCode, wardCode, amenityIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingControllerApi.getListings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {ListingUpsertRequest} listingUpsertRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateListing(id: string, listingUpsertRequest: ListingUpsertRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseString>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateListing(id, listingUpsertRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingControllerApi.updateListing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ListingControllerApi - factory interface
 */
export const ListingControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ListingControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {ListingControllerApiCreateListingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createListing(requestParameters: ListingControllerApiCreateListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseString> {
            return localVarFp.createListing(requestParameters.listingUpsertRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ListingControllerApiDeleteListingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteListing(requestParameters: ListingControllerApiDeleteListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseString> {
            return localVarFp.deleteListing(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ListingControllerApiGetListingDetailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingDetail(requestParameters: ListingControllerApiGetListingDetailRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListingDetailResponse> {
            return localVarFp.getListingDetail(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ListingControllerApiGetListingsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListings(requestParameters: ListingControllerApiGetListingsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageListingSummaryResponse> {
            return localVarFp.getListings(requestParameters.listingType, requestParameters.page, requestParameters.size, requestParameters.sort, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.minBedrooms, requestParameters.maxBedrooms, requestParameters.minBathrooms, requestParameters.maxBathrooms, requestParameters.minArea, requestParameters.maxArea, requestParameters.title, requestParameters.provinceCode, requestParameters.wardCode, requestParameters.amenityIds, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ListingControllerApiUpdateListingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateListing(requestParameters: ListingControllerApiUpdateListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseString> {
            return localVarFp.updateListing(requestParameters.id, requestParameters.listingUpsertRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ListingControllerApi - interface
 */
export interface ListingControllerApiInterface {
    /**
     * 
     * @param {ListingControllerApiCreateListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createListing(requestParameters: ListingControllerApiCreateListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseString>;

    /**
     * 
     * @param {ListingControllerApiDeleteListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteListing(requestParameters: ListingControllerApiDeleteListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseString>;

    /**
     * 
     * @param {ListingControllerApiGetListingDetailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getListingDetail(requestParameters: ListingControllerApiGetListingDetailRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListingDetailResponse>;

    /**
     * 
     * @param {ListingControllerApiGetListingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getListings(requestParameters: ListingControllerApiGetListingsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageListingSummaryResponse>;

    /**
     * 
     * @param {ListingControllerApiUpdateListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateListing(requestParameters: ListingControllerApiUpdateListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseString>;

}

/**
 * Request parameters for createListing operation in ListingControllerApi.
 */
export interface ListingControllerApiCreateListingRequest {
    readonly listingUpsertRequest: ListingUpsertRequest
}

/**
 * Request parameters for deleteListing operation in ListingControllerApi.
 */
export interface ListingControllerApiDeleteListingRequest {
    readonly id: string
}

/**
 * Request parameters for getListingDetail operation in ListingControllerApi.
 */
export interface ListingControllerApiGetListingDetailRequest {
    readonly id: string
}

/**
 * Request parameters for getListings operation in ListingControllerApi.
 */
export interface ListingControllerApiGetListingsRequest {
    readonly listingType: GetListingsListingTypeEnum

    /**
     * Zero-based page index (0..N)
     */
    readonly page?: number

    /**
     * The size of the page to be returned
     */
    readonly size?: number

    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    readonly sort?: Array<string>

    readonly minPrice?: number

    readonly maxPrice?: number

    readonly minBedrooms?: number

    readonly maxBedrooms?: number

    readonly minBathrooms?: number

    readonly maxBathrooms?: number

    readonly minArea?: number

    readonly maxArea?: number

    readonly title?: string

    readonly provinceCode?: string

    readonly wardCode?: string

    readonly amenityIds?: Array<number>
}

/**
 * Request parameters for updateListing operation in ListingControllerApi.
 */
export interface ListingControllerApiUpdateListingRequest {
    readonly id: string

    readonly listingUpsertRequest: ListingUpsertRequest
}

/**
 * ListingControllerApi - object-oriented interface
 */
export class ListingControllerApi extends BaseAPI implements ListingControllerApiInterface {
    /**
     * 
     * @param {ListingControllerApiCreateListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createListing(requestParameters: ListingControllerApiCreateListingRequest, options?: RawAxiosRequestConfig) {
        return ListingControllerApiFp(this.configuration).createListing(requestParameters.listingUpsertRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ListingControllerApiDeleteListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteListing(requestParameters: ListingControllerApiDeleteListingRequest, options?: RawAxiosRequestConfig) {
        return ListingControllerApiFp(this.configuration).deleteListing(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ListingControllerApiGetListingDetailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getListingDetail(requestParameters: ListingControllerApiGetListingDetailRequest, options?: RawAxiosRequestConfig) {
        return ListingControllerApiFp(this.configuration).getListingDetail(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ListingControllerApiGetListingsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getListings(requestParameters: ListingControllerApiGetListingsRequest, options?: RawAxiosRequestConfig) {
        return ListingControllerApiFp(this.configuration).getListings(requestParameters.listingType, requestParameters.page, requestParameters.size, requestParameters.sort, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.minBedrooms, requestParameters.maxBedrooms, requestParameters.minBathrooms, requestParameters.maxBathrooms, requestParameters.minArea, requestParameters.maxArea, requestParameters.title, requestParameters.provinceCode, requestParameters.wardCode, requestParameters.amenityIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ListingControllerApiUpdateListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateListing(requestParameters: ListingControllerApiUpdateListingRequest, options?: RawAxiosRequestConfig) {
        return ListingControllerApiFp(this.configuration).updateListing(requestParameters.id, requestParameters.listingUpsertRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetListingsListingTypeEnum = {
    ForSale: 'FOR_SALE',
    ForRent: 'FOR_RENT',
} as const;
export type GetListingsListingTypeEnum = typeof GetListingsListingTypeEnum[keyof typeof GetListingsListingTypeEnum];
