/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
/**
 * ListingViewsApi - axios parameter creator
 */
export const ListingViewsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Dedup theo IP/ngày UTC (chống F5 bot), INCR Redis buffer kèm metadata IP/user. Cron flush: Lua GETDEL count + snapshot events → INSERT listing_views.
         * @summary Ghi nhận lượt xem
         * @param {string} listingId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerView: async (listingId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listingId' is not null or undefined
            assertParamExists('registerView', 'listingId', listingId)
            const localVarPath = `/listing/{listingId}/views`
                .replace('{listingId}', encodeURIComponent(String(listingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ListingViewsApi - functional programming interface
 */
export const ListingViewsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ListingViewsApiAxiosParamCreator(configuration)
    return {
        /**
         * Dedup theo IP/ngày UTC (chống F5 bot), INCR Redis buffer kèm metadata IP/user. Cron flush: Lua GETDEL count + snapshot events → INSERT listing_views.
         * @summary Ghi nhận lượt xem
         * @param {string} listingId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerView(listingId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerView(listingId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingViewsApi.registerView']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ListingViewsApi - factory interface
 */
export const ListingViewsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ListingViewsApiFp(configuration)
    return {
        /**
         * Dedup theo IP/ngày UTC (chống F5 bot), INCR Redis buffer kèm metadata IP/user. Cron flush: Lua GETDEL count + snapshot events → INSERT listing_views.
         * @summary Ghi nhận lượt xem
         * @param {ListingViewsApiRegisterViewRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerView(requestParameters: ListingViewsApiRegisterViewRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.registerView(requestParameters.listingId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ListingViewsApi - interface
 */
export interface ListingViewsApiInterface {
    /**
     * Dedup theo IP/ngày UTC (chống F5 bot), INCR Redis buffer kèm metadata IP/user. Cron flush: Lua GETDEL count + snapshot events → INSERT listing_views.
     * @summary Ghi nhận lượt xem
     * @param {ListingViewsApiRegisterViewRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerView(requestParameters: ListingViewsApiRegisterViewRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid>;

}

/**
 * Request parameters for registerView operation in ListingViewsApi.
 */
export interface ListingViewsApiRegisterViewRequest {
    readonly listingId: string
}

/**
 * ListingViewsApi - object-oriented interface
 */
export class ListingViewsApi extends BaseAPI implements ListingViewsApiInterface {
    /**
     * Dedup theo IP/ngày UTC (chống F5 bot), INCR Redis buffer kèm metadata IP/user. Cron flush: Lua GETDEL count + snapshot events → INSERT listing_views.
     * @summary Ghi nhận lượt xem
     * @param {ListingViewsApiRegisterViewRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerView(requestParameters: ListingViewsApiRegisterViewRequest, options?: RawAxiosRequestConfig) {
        return ListingViewsApiFp(this.configuration).registerView(requestParameters.listingId, options).then((request) => request(this.axios, this.basePath));
    }
}

