/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseConversationResponse } from '../models';
// @ts-ignore
import type { ApiResponseListConversationResponse } from '../models';
// @ts-ignore
import type { ApiResponseMessageResponse } from '../models';
// @ts-ignore
import type { ApiResponseSliceMessageResponse } from '../models';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
// @ts-ignore
import type { Pageable } from '../models';
// @ts-ignore
import type { SendMessageRequest } from '../models';
/**
 * MessagingApi - axios parameter creator
 */
export const MessagingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns all active conversations for the authenticated user with per-user unreadCount.
         * @summary List user conversations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConversations: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/messages/conversations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a paginated Slice of messages (sorted DESC by createdAt to show newest first).
         * @summary Get message history
         * @param {string} conversationId 
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessages: async (conversationId: string, pageable: Pageable, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'conversationId' is not null or undefined
            assertParamExists('getMessages', 'conversationId', conversationId)
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getMessages', 'pageable', pageable)
            const localVarPath = `/messages/conversations/{conversationId}/messages`
                .replace('{conversationId}', encodeURIComponent(String(conversationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Marks all unread messages (sent by others) in the conversation as read and resets the caller\'s unread counter.
         * @summary Mark messages as read
         * @param {string} conversationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAsRead1: async (conversationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'conversationId' is not null or undefined
            assertParamExists('markAsRead1', 'conversationId', conversationId)
            const localVarPath = `/messages/conversations/{conversationId}/read`
                .replace('{conversationId}', encodeURIComponent(String(conversationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Saves a message and broadcasts it to /topic/conversation/{conversationId} via STOMP.
         * @summary Send message (REST)
         * @param {string} conversationId 
         * @param {SendMessageRequest} sendMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessage: async (conversationId: string, sendMessageRequest: SendMessageRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'conversationId' is not null or undefined
            assertParamExists('sendMessage', 'conversationId', conversationId)
            // verify required parameter 'sendMessageRequest' is not null or undefined
            assertParamExists('sendMessage', 'sendMessageRequest', sendMessageRequest)
            const localVarPath = `/messages/conversations/{conversationId}/messages`
                .replace('{conversationId}', encodeURIComponent(String(conversationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendMessageRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns an existing conversation or creates one. Handles both client-initiated and host-initiated starts.
         * @summary Start or get conversation
         * @param {string} listingId 
         * @param {string} participantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startConversation: async (listingId: string, participantId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listingId' is not null or undefined
            assertParamExists('startConversation', 'listingId', listingId)
            // verify required parameter 'participantId' is not null or undefined
            assertParamExists('startConversation', 'participantId', participantId)
            const localVarPath = `/messages/conversations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (listingId !== undefined) {
                localVarQueryParameter['listingId'] = listingId;
            }

            if (participantId !== undefined) {
                localVarQueryParameter['participantId'] = participantId;
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MessagingApi - functional programming interface
 */
export const MessagingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MessagingApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns all active conversations for the authenticated user with per-user unreadCount.
         * @summary List user conversations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getConversations(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseListConversationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getConversations(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagingApi.getConversations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a paginated Slice of messages (sorted DESC by createdAt to show newest first).
         * @summary Get message history
         * @param {string} conversationId 
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMessages(conversationId: string, pageable: Pageable, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseSliceMessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMessages(conversationId, pageable, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagingApi.getMessages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Marks all unread messages (sent by others) in the conversation as read and resets the caller\'s unread counter.
         * @summary Mark messages as read
         * @param {string} conversationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markAsRead1(conversationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markAsRead1(conversationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagingApi.markAsRead1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Saves a message and broadcasts it to /topic/conversation/{conversationId} via STOMP.
         * @summary Send message (REST)
         * @param {string} conversationId 
         * @param {SendMessageRequest} sendMessageRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendMessage(conversationId: string, sendMessageRequest: SendMessageRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseMessageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendMessage(conversationId, sendMessageRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagingApi.sendMessage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns an existing conversation or creates one. Handles both client-initiated and host-initiated starts.
         * @summary Start or get conversation
         * @param {string} listingId 
         * @param {string} participantId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startConversation(listingId: string, participantId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseConversationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startConversation(listingId, participantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessagingApi.startConversation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MessagingApi - factory interface
 */
export const MessagingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MessagingApiFp(configuration)
    return {
        /**
         * Returns all active conversations for the authenticated user with per-user unreadCount.
         * @summary List user conversations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getConversations(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListConversationResponse> {
            return localVarFp.getConversations(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a paginated Slice of messages (sorted DESC by createdAt to show newest first).
         * @summary Get message history
         * @param {MessagingApiGetMessagesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessages(requestParameters: MessagingApiGetMessagesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSliceMessageResponse> {
            return localVarFp.getMessages(requestParameters.conversationId, requestParameters.pageable, options).then((request) => request(axios, basePath));
        },
        /**
         * Marks all unread messages (sent by others) in the conversation as read and resets the caller\'s unread counter.
         * @summary Mark messages as read
         * @param {MessagingApiMarkAsRead1Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAsRead1(requestParameters: MessagingApiMarkAsRead1Request, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.markAsRead1(requestParameters.conversationId, options).then((request) => request(axios, basePath));
        },
        /**
         * Saves a message and broadcasts it to /topic/conversation/{conversationId} via STOMP.
         * @summary Send message (REST)
         * @param {MessagingApiSendMessageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendMessage(requestParameters: MessagingApiSendMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseMessageResponse> {
            return localVarFp.sendMessage(requestParameters.conversationId, requestParameters.sendMessageRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns an existing conversation or creates one. Handles both client-initiated and host-initiated starts.
         * @summary Start or get conversation
         * @param {MessagingApiStartConversationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startConversation(requestParameters: MessagingApiStartConversationRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseConversationResponse> {
            return localVarFp.startConversation(requestParameters.listingId, requestParameters.participantId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MessagingApi - interface
 */
export interface MessagingApiInterface {
    /**
     * Returns all active conversations for the authenticated user with per-user unreadCount.
     * @summary List user conversations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getConversations(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseListConversationResponse>;

    /**
     * Returns a paginated Slice of messages (sorted DESC by createdAt to show newest first).
     * @summary Get message history
     * @param {MessagingApiGetMessagesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMessages(requestParameters: MessagingApiGetMessagesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseSliceMessageResponse>;

    /**
     * Marks all unread messages (sent by others) in the conversation as read and resets the caller\'s unread counter.
     * @summary Mark messages as read
     * @param {MessagingApiMarkAsRead1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    markAsRead1(requestParameters: MessagingApiMarkAsRead1Request, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid>;

    /**
     * Saves a message and broadcasts it to /topic/conversation/{conversationId} via STOMP.
     * @summary Send message (REST)
     * @param {MessagingApiSendMessageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendMessage(requestParameters: MessagingApiSendMessageRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseMessageResponse>;

    /**
     * Returns an existing conversation or creates one. Handles both client-initiated and host-initiated starts.
     * @summary Start or get conversation
     * @param {MessagingApiStartConversationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    startConversation(requestParameters: MessagingApiStartConversationRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseConversationResponse>;

}

/**
 * Request parameters for getMessages operation in MessagingApi.
 */
export interface MessagingApiGetMessagesRequest {
    readonly conversationId: string

    readonly pageable: Pageable
}

/**
 * Request parameters for markAsRead1 operation in MessagingApi.
 */
export interface MessagingApiMarkAsRead1Request {
    readonly conversationId: string
}

/**
 * Request parameters for sendMessage operation in MessagingApi.
 */
export interface MessagingApiSendMessageRequest {
    readonly conversationId: string

    readonly sendMessageRequest: SendMessageRequest
}

/**
 * Request parameters for startConversation operation in MessagingApi.
 */
export interface MessagingApiStartConversationRequest {
    readonly listingId: string

    readonly participantId: string
}

/**
 * MessagingApi - object-oriented interface
 */
export class MessagingApi extends BaseAPI implements MessagingApiInterface {
    /**
     * Returns all active conversations for the authenticated user with per-user unreadCount.
     * @summary List user conversations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getConversations(options?: RawAxiosRequestConfig) {
        return MessagingApiFp(this.configuration).getConversations(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a paginated Slice of messages (sorted DESC by createdAt to show newest first).
     * @summary Get message history
     * @param {MessagingApiGetMessagesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMessages(requestParameters: MessagingApiGetMessagesRequest, options?: RawAxiosRequestConfig) {
        return MessagingApiFp(this.configuration).getMessages(requestParameters.conversationId, requestParameters.pageable, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Marks all unread messages (sent by others) in the conversation as read and resets the caller\'s unread counter.
     * @summary Mark messages as read
     * @param {MessagingApiMarkAsRead1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public markAsRead1(requestParameters: MessagingApiMarkAsRead1Request, options?: RawAxiosRequestConfig) {
        return MessagingApiFp(this.configuration).markAsRead1(requestParameters.conversationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Saves a message and broadcasts it to /topic/conversation/{conversationId} via STOMP.
     * @summary Send message (REST)
     * @param {MessagingApiSendMessageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sendMessage(requestParameters: MessagingApiSendMessageRequest, options?: RawAxiosRequestConfig) {
        return MessagingApiFp(this.configuration).sendMessage(requestParameters.conversationId, requestParameters.sendMessageRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns an existing conversation or creates one. Handles both client-initiated and host-initiated starts.
     * @summary Start or get conversation
     * @param {MessagingApiStartConversationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public startConversation(requestParameters: MessagingApiStartConversationRequest, options?: RawAxiosRequestConfig) {
        return MessagingApiFp(this.configuration).startConversation(requestParameters.listingId, requestParameters.participantId, options).then((request) => request(this.axios, this.basePath));
    }
}

