/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseLong } from '../models';
// @ts-ignore
import type { ApiResponseNotificationResponse } from '../models';
// @ts-ignore
import type { ApiResponsePageNotificationResponse } from '../models';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
// @ts-ignore
import type { Pageable } from '../models';
/**
 * NotificationsApi - axios parameter creator
 */
export const NotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Lấy tổng số thông báo chưa đọc để hiển thị badge
         * @summary Lấy số lượng thông báo chưa đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUnreadCount: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notifications/unread-count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lấy danh sách thông báo của người dùng hiện tại có phân trang
         * @summary Lấy danh sách thông báo
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserNotifications: async (pageable: Pageable, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getUserNotifications', 'pageable', pageable)
            const localVarPath = `/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Cập nhật trạng thái tất cả thông báo của người dùng hiện tại sang đã đọc
         * @summary Đánh dấu tất cả thông báo là đã đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAllAsRead: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notifications/read-all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Cập nhật trạng thái một thông báo cụ thể sang đã đọc
         * @summary Đánh dấu một thông báo là đã đọc
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAsRead: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('markAsRead', 'id', id)
            const localVarPath = `/notifications/{id}/read`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationsApi - functional programming interface
 */
export const NotificationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationsApiAxiosParamCreator(configuration)
    return {
        /**
         * Lấy tổng số thông báo chưa đọc để hiển thị badge
         * @summary Lấy số lượng thông báo chưa đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUnreadCount(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUnreadCount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.getUnreadCount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Lấy danh sách thông báo của người dùng hiện tại có phân trang
         * @summary Lấy danh sách thông báo
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserNotifications(pageable: Pageable, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageNotificationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserNotifications(pageable, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.getUserNotifications']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Cập nhật trạng thái tất cả thông báo của người dùng hiện tại sang đã đọc
         * @summary Đánh dấu tất cả thông báo là đã đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markAllAsRead(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markAllAsRead(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.markAllAsRead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Cập nhật trạng thái một thông báo cụ thể sang đã đọc
         * @summary Đánh dấu một thông báo là đã đọc
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markAsRead(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseNotificationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.markAsRead(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.markAsRead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotificationsApi - factory interface
 */
export const NotificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationsApiFp(configuration)
    return {
        /**
         * Lấy tổng số thông báo chưa đọc để hiển thị badge
         * @summary Lấy số lượng thông báo chưa đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUnreadCount(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseLong> {
            return localVarFp.getUnreadCount(options).then((request) => request(axios, basePath));
        },
        /**
         * Lấy danh sách thông báo của người dùng hiện tại có phân trang
         * @summary Lấy danh sách thông báo
         * @param {NotificationsApiGetUserNotificationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserNotifications(requestParameters: NotificationsApiGetUserNotificationsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageNotificationResponse> {
            return localVarFp.getUserNotifications(requestParameters.pageable, options).then((request) => request(axios, basePath));
        },
        /**
         * Cập nhật trạng thái tất cả thông báo của người dùng hiện tại sang đã đọc
         * @summary Đánh dấu tất cả thông báo là đã đọc
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAllAsRead(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.markAllAsRead(options).then((request) => request(axios, basePath));
        },
        /**
         * Cập nhật trạng thái một thông báo cụ thể sang đã đọc
         * @summary Đánh dấu một thông báo là đã đọc
         * @param {NotificationsApiMarkAsReadRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markAsRead(requestParameters: NotificationsApiMarkAsReadRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseNotificationResponse> {
            return localVarFp.markAsRead(requestParameters.id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationsApi - interface
 */
export interface NotificationsApiInterface {
    /**
     * Lấy tổng số thông báo chưa đọc để hiển thị badge
     * @summary Lấy số lượng thông báo chưa đọc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUnreadCount(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseLong>;

    /**
     * Lấy danh sách thông báo của người dùng hiện tại có phân trang
     * @summary Lấy danh sách thông báo
     * @param {NotificationsApiGetUserNotificationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserNotifications(requestParameters: NotificationsApiGetUserNotificationsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageNotificationResponse>;

    /**
     * Cập nhật trạng thái tất cả thông báo của người dùng hiện tại sang đã đọc
     * @summary Đánh dấu tất cả thông báo là đã đọc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    markAllAsRead(options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid>;

    /**
     * Cập nhật trạng thái một thông báo cụ thể sang đã đọc
     * @summary Đánh dấu một thông báo là đã đọc
     * @param {NotificationsApiMarkAsReadRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    markAsRead(requestParameters: NotificationsApiMarkAsReadRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseNotificationResponse>;

}

/**
 * Request parameters for getUserNotifications operation in NotificationsApi.
 */
export interface NotificationsApiGetUserNotificationsRequest {
    readonly pageable: Pageable
}

/**
 * Request parameters for markAsRead operation in NotificationsApi.
 */
export interface NotificationsApiMarkAsReadRequest {
    readonly id: string
}

/**
 * NotificationsApi - object-oriented interface
 */
export class NotificationsApi extends BaseAPI implements NotificationsApiInterface {
    /**
     * Lấy tổng số thông báo chưa đọc để hiển thị badge
     * @summary Lấy số lượng thông báo chưa đọc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUnreadCount(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).getUnreadCount(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lấy danh sách thông báo của người dùng hiện tại có phân trang
     * @summary Lấy danh sách thông báo
     * @param {NotificationsApiGetUserNotificationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUserNotifications(requestParameters: NotificationsApiGetUserNotificationsRequest, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).getUserNotifications(requestParameters.pageable, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Cập nhật trạng thái tất cả thông báo của người dùng hiện tại sang đã đọc
     * @summary Đánh dấu tất cả thông báo là đã đọc
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public markAllAsRead(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).markAllAsRead(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Cập nhật trạng thái một thông báo cụ thể sang đã đọc
     * @summary Đánh dấu một thông báo là đã đọc
     * @param {NotificationsApiMarkAsReadRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public markAsRead(requestParameters: NotificationsApiMarkAsReadRequest, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).markAsRead(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }
}

