/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponsePushTokenResponse } from '../models';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
// @ts-ignore
import type { UpsertPushTokenRequest } from '../models';
/**
 * PushNotificationsApi - axios parameter creator
 */
export const PushNotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Vô hiệu hóa push token của thiết bị khi người dùng đăng xuất
         * @summary Hủy Push Token theo deviceId
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivatePushToken: async (deviceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deviceId' is not null or undefined
            assertParamExists('deactivatePushToken', 'deviceId', deviceId)
            const localVarPath = `/notifications/tokens/{deviceId}`
                .replace('{deviceId}', encodeURIComponent(String(deviceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Đăng ký hoặc cập nhật FCM/WEB push token cho thiết bị của người dùng hiện tại
         * @summary Lưu hoặc cập nhật Push Token
         * @param {UpsertPushTokenRequest} upsertPushTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertPushToken: async (upsertPushTokenRequest: UpsertPushTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'upsertPushTokenRequest' is not null or undefined
            assertParamExists('upsertPushToken', 'upsertPushTokenRequest', upsertPushTokenRequest)
            const localVarPath = `/notifications/tokens`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertPushTokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PushNotificationsApi - functional programming interface
 */
export const PushNotificationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PushNotificationsApiAxiosParamCreator(configuration)
    return {
        /**
         * Vô hiệu hóa push token của thiết bị khi người dùng đăng xuất
         * @summary Hủy Push Token theo deviceId
         * @param {string} deviceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deactivatePushToken(deviceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deactivatePushToken(deviceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PushNotificationsApi.deactivatePushToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Đăng ký hoặc cập nhật FCM/WEB push token cho thiết bị của người dùng hiện tại
         * @summary Lưu hoặc cập nhật Push Token
         * @param {UpsertPushTokenRequest} upsertPushTokenRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async upsertPushToken(upsertPushTokenRequest: UpsertPushTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePushTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.upsertPushToken(upsertPushTokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PushNotificationsApi.upsertPushToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PushNotificationsApi - factory interface
 */
export const PushNotificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PushNotificationsApiFp(configuration)
    return {
        /**
         * Vô hiệu hóa push token của thiết bị khi người dùng đăng xuất
         * @summary Hủy Push Token theo deviceId
         * @param {PushNotificationsApiDeactivatePushTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivatePushToken(requestParameters: PushNotificationsApiDeactivatePushTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.deactivatePushToken(requestParameters.deviceId, options).then((request) => request(axios, basePath));
        },
        /**
         * Đăng ký hoặc cập nhật FCM/WEB push token cho thiết bị của người dùng hiện tại
         * @summary Lưu hoặc cập nhật Push Token
         * @param {PushNotificationsApiUpsertPushTokenRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertPushToken(requestParameters: PushNotificationsApiUpsertPushTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePushTokenResponse> {
            return localVarFp.upsertPushToken(requestParameters.upsertPushTokenRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PushNotificationsApi - interface
 */
export interface PushNotificationsApiInterface {
    /**
     * Vô hiệu hóa push token của thiết bị khi người dùng đăng xuất
     * @summary Hủy Push Token theo deviceId
     * @param {PushNotificationsApiDeactivatePushTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deactivatePushToken(requestParameters: PushNotificationsApiDeactivatePushTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid>;

    /**
     * Đăng ký hoặc cập nhật FCM/WEB push token cho thiết bị của người dùng hiện tại
     * @summary Lưu hoặc cập nhật Push Token
     * @param {PushNotificationsApiUpsertPushTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    upsertPushToken(requestParameters: PushNotificationsApiUpsertPushTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePushTokenResponse>;

}

/**
 * Request parameters for deactivatePushToken operation in PushNotificationsApi.
 */
export interface PushNotificationsApiDeactivatePushTokenRequest {
    readonly deviceId: string
}

/**
 * Request parameters for upsertPushToken operation in PushNotificationsApi.
 */
export interface PushNotificationsApiUpsertPushTokenRequest {
    readonly upsertPushTokenRequest: UpsertPushTokenRequest
}

/**
 * PushNotificationsApi - object-oriented interface
 */
export class PushNotificationsApi extends BaseAPI implements PushNotificationsApiInterface {
    /**
     * Vô hiệu hóa push token của thiết bị khi người dùng đăng xuất
     * @summary Hủy Push Token theo deviceId
     * @param {PushNotificationsApiDeactivatePushTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deactivatePushToken(requestParameters: PushNotificationsApiDeactivatePushTokenRequest, options?: RawAxiosRequestConfig) {
        return PushNotificationsApiFp(this.configuration).deactivatePushToken(requestParameters.deviceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Đăng ký hoặc cập nhật FCM/WEB push token cho thiết bị của người dùng hiện tại
     * @summary Lưu hoặc cập nhật Push Token
     * @param {PushNotificationsApiUpsertPushTokenRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public upsertPushToken(requestParameters: PushNotificationsApiUpsertPushTokenRequest, options?: RawAxiosRequestConfig) {
        return PushNotificationsApiFp(this.configuration).upsertPushToken(requestParameters.upsertPushTokenRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

