/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponsePageReviewResponse } from '../models';
// @ts-ignore
import type { ApiResponseReviewResponse } from '../models';
// @ts-ignore
import type { ApiResponseVoid } from '../models';
// @ts-ignore
import type { CreateReportRequest } from '../models';
// @ts-ignore
import type { CreateReviewRequest } from '../models';
// @ts-ignore
import type { Pageable } from '../models';
// @ts-ignore
import type { ReplyToReviewRequest } from '../models';
/**
 * ReviewsApi - axios parameter creator
 */
export const ReviewsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Submit a review for a listing. A COMPLETED viewing schedule for that listing is required.
         * @summary Create a verified review
         * @param {CreateReviewRequest} createReviewRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReview: async (createReviewRequest: CreateReviewRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createReviewRequest' is not null or undefined
            assertParamExists('createReview', 'createReviewRequest', createReviewRequest)
            const localVarPath = `/reviews`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createReviewRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all visible, non-hidden reviews for the given listing, paginated.
         * @summary Get paginated feedback for a listing
         * @param {string} listingId 
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingFeedback: async (listingId: string, pageable: Pageable, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'listingId' is not null or undefined
            assertParamExists('getListingFeedback', 'listingId', listingId)
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getListingFeedback', 'pageable', pageable)
            const localVarPath = `/reviews/listing/{listingId}/feedback`
                .replace('{listingId}', encodeURIComponent(String(listingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve paginated reviews filtered by listingId or hostId. Provide exactly one of the two query parameters.
         * @summary List reviews
         * @param {Pageable} pageable 
         * @param {string} [listingId] Filter reviews by listing ID
         * @param {string} [hostId] Filter reviews by host user ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReviews: async (pageable: Pageable, listingId?: string, hostId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getReviews', 'pageable', pageable)
            const localVarPath = `/reviews`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (listingId !== undefined) {
                localVarQueryParameter['listingId'] = listingId;
            }

            if (hostId !== undefined) {
                localVarQueryParameter['hostId'] = hostId;
            }

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * The host of the listing may post a single reply to a review. Only the listing host is authorised. Editing an existing reply is not supported.
         * @summary Host replies to a review
         * @param {string} reviewId 
         * @param {ReplyToReviewRequest} replyToReviewRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replyToReview: async (reviewId: string, replyToReviewRequest: ReplyToReviewRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reviewId' is not null or undefined
            assertParamExists('replyToReview', 'reviewId', reviewId)
            // verify required parameter 'replyToReviewRequest' is not null or undefined
            assertParamExists('replyToReview', 'replyToReviewRequest', replyToReviewRequest)
            const localVarPath = `/reviews/{reviewId}/reply`
                .replace('{reviewId}', encodeURIComponent(String(reviewId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(replyToReviewRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Submit a fraud / inaccuracy / inappropriate-content report for a listing. Allowed reasons: FRAUD, DUPLICATE, WRONG_INFO, INAPPROPRIATE_CONTENT, WRONG_PRICE, ALREADY_RENTED, OTHER.
         * @summary Report a listing
         * @param {CreateReportRequest} createReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportListing: async (createReportRequest: CreateReportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createReportRequest' is not null or undefined
            assertParamExists('reportListing', 'createReportRequest', createReportRequest)
            const localVarPath = `/reports`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createReportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReviewsApi - functional programming interface
 */
export const ReviewsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReviewsApiAxiosParamCreator(configuration)
    return {
        /**
         * Submit a review for a listing. A COMPLETED viewing schedule for that listing is required.
         * @summary Create a verified review
         * @param {CreateReviewRequest} createReviewRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createReview(createReviewRequest: CreateReviewRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseReviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createReview(createReviewRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewsApi.createReview']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns all visible, non-hidden reviews for the given listing, paginated.
         * @summary Get paginated feedback for a listing
         * @param {string} listingId 
         * @param {Pageable} pageable 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListingFeedback(listingId: string, pageable: Pageable, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageReviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getListingFeedback(listingId, pageable, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewsApi.getListingFeedback']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve paginated reviews filtered by listingId or hostId. Provide exactly one of the two query parameters.
         * @summary List reviews
         * @param {Pageable} pageable 
         * @param {string} [listingId] Filter reviews by listing ID
         * @param {string} [hostId] Filter reviews by host user ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReviews(pageable: Pageable, listingId?: string, hostId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageReviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReviews(pageable, listingId, hostId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewsApi.getReviews']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * The host of the listing may post a single reply to a review. Only the listing host is authorised. Editing an existing reply is not supported.
         * @summary Host replies to a review
         * @param {string} reviewId 
         * @param {ReplyToReviewRequest} replyToReviewRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async replyToReview(reviewId: string, replyToReviewRequest: ReplyToReviewRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseReviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.replyToReview(reviewId, replyToReviewRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewsApi.replyToReview']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Submit a fraud / inaccuracy / inappropriate-content report for a listing. Allowed reasons: FRAUD, DUPLICATE, WRONG_INFO, INAPPROPRIATE_CONTENT, WRONG_PRICE, ALREADY_RENTED, OTHER.
         * @summary Report a listing
         * @param {CreateReportRequest} createReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reportListing(createReportRequest: CreateReportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reportListing(createReportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReviewsApi.reportListing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReviewsApi - factory interface
 */
export const ReviewsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReviewsApiFp(configuration)
    return {
        /**
         * Submit a review for a listing. A COMPLETED viewing schedule for that listing is required.
         * @summary Create a verified review
         * @param {ReviewsApiCreateReviewRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReview(requestParameters: ReviewsApiCreateReviewRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseReviewResponse> {
            return localVarFp.createReview(requestParameters.createReviewRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all visible, non-hidden reviews for the given listing, paginated.
         * @summary Get paginated feedback for a listing
         * @param {ReviewsApiGetListingFeedbackRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListingFeedback(requestParameters: ReviewsApiGetListingFeedbackRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageReviewResponse> {
            return localVarFp.getListingFeedback(requestParameters.listingId, requestParameters.pageable, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve paginated reviews filtered by listingId or hostId. Provide exactly one of the two query parameters.
         * @summary List reviews
         * @param {ReviewsApiGetReviewsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReviews(requestParameters: ReviewsApiGetReviewsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageReviewResponse> {
            return localVarFp.getReviews(requestParameters.pageable, requestParameters.listingId, requestParameters.hostId, options).then((request) => request(axios, basePath));
        },
        /**
         * The host of the listing may post a single reply to a review. Only the listing host is authorised. Editing an existing reply is not supported.
         * @summary Host replies to a review
         * @param {ReviewsApiReplyToReviewRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replyToReview(requestParameters: ReviewsApiReplyToReviewRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseReviewResponse> {
            return localVarFp.replyToReview(requestParameters.reviewId, requestParameters.replyToReviewRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Submit a fraud / inaccuracy / inappropriate-content report for a listing. Allowed reasons: FRAUD, DUPLICATE, WRONG_INFO, INAPPROPRIATE_CONTENT, WRONG_PRICE, ALREADY_RENTED, OTHER.
         * @summary Report a listing
         * @param {ReviewsApiReportListingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportListing(requestParameters: ReviewsApiReportListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid> {
            return localVarFp.reportListing(requestParameters.createReportRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReviewsApi - interface
 */
export interface ReviewsApiInterface {
    /**
     * Submit a review for a listing. A COMPLETED viewing schedule for that listing is required.
     * @summary Create a verified review
     * @param {ReviewsApiCreateReviewRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createReview(requestParameters: ReviewsApiCreateReviewRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseReviewResponse>;

    /**
     * Returns all visible, non-hidden reviews for the given listing, paginated.
     * @summary Get paginated feedback for a listing
     * @param {ReviewsApiGetListingFeedbackRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getListingFeedback(requestParameters: ReviewsApiGetListingFeedbackRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageReviewResponse>;

    /**
     * Retrieve paginated reviews filtered by listingId or hostId. Provide exactly one of the two query parameters.
     * @summary List reviews
     * @param {ReviewsApiGetReviewsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getReviews(requestParameters: ReviewsApiGetReviewsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageReviewResponse>;

    /**
     * The host of the listing may post a single reply to a review. Only the listing host is authorised. Editing an existing reply is not supported.
     * @summary Host replies to a review
     * @param {ReviewsApiReplyToReviewRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    replyToReview(requestParameters: ReviewsApiReplyToReviewRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseReviewResponse>;

    /**
     * Submit a fraud / inaccuracy / inappropriate-content report for a listing. Allowed reasons: FRAUD, DUPLICATE, WRONG_INFO, INAPPROPRIATE_CONTENT, WRONG_PRICE, ALREADY_RENTED, OTHER.
     * @summary Report a listing
     * @param {ReviewsApiReportListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reportListing(requestParameters: ReviewsApiReportListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseVoid>;

}

/**
 * Request parameters for createReview operation in ReviewsApi.
 */
export interface ReviewsApiCreateReviewRequest {
    readonly createReviewRequest: CreateReviewRequest
}

/**
 * Request parameters for getListingFeedback operation in ReviewsApi.
 */
export interface ReviewsApiGetListingFeedbackRequest {
    readonly listingId: string

    readonly pageable: Pageable
}

/**
 * Request parameters for getReviews operation in ReviewsApi.
 */
export interface ReviewsApiGetReviewsRequest {
    readonly pageable: Pageable

    /**
     * Filter reviews by listing ID
     */
    readonly listingId?: string

    /**
     * Filter reviews by host user ID
     */
    readonly hostId?: string
}

/**
 * Request parameters for replyToReview operation in ReviewsApi.
 */
export interface ReviewsApiReplyToReviewRequest {
    readonly reviewId: string

    readonly replyToReviewRequest: ReplyToReviewRequest
}

/**
 * Request parameters for reportListing operation in ReviewsApi.
 */
export interface ReviewsApiReportListingRequest {
    readonly createReportRequest: CreateReportRequest
}

/**
 * ReviewsApi - object-oriented interface
 */
export class ReviewsApi extends BaseAPI implements ReviewsApiInterface {
    /**
     * Submit a review for a listing. A COMPLETED viewing schedule for that listing is required.
     * @summary Create a verified review
     * @param {ReviewsApiCreateReviewRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createReview(requestParameters: ReviewsApiCreateReviewRequest, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).createReview(requestParameters.createReviewRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all visible, non-hidden reviews for the given listing, paginated.
     * @summary Get paginated feedback for a listing
     * @param {ReviewsApiGetListingFeedbackRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getListingFeedback(requestParameters: ReviewsApiGetListingFeedbackRequest, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).getListingFeedback(requestParameters.listingId, requestParameters.pageable, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve paginated reviews filtered by listingId or hostId. Provide exactly one of the two query parameters.
     * @summary List reviews
     * @param {ReviewsApiGetReviewsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getReviews(requestParameters: ReviewsApiGetReviewsRequest, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).getReviews(requestParameters.pageable, requestParameters.listingId, requestParameters.hostId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * The host of the listing may post a single reply to a review. Only the listing host is authorised. Editing an existing reply is not supported.
     * @summary Host replies to a review
     * @param {ReviewsApiReplyToReviewRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public replyToReview(requestParameters: ReviewsApiReplyToReviewRequest, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).replyToReview(requestParameters.reviewId, requestParameters.replyToReviewRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Submit a fraud / inaccuracy / inappropriate-content report for a listing. Allowed reasons: FRAUD, DUPLICATE, WRONG_INFO, INAPPROPRIATE_CONTENT, WRONG_PRICE, ALREADY_RENTED, OTHER.
     * @summary Report a listing
     * @param {ReviewsApiReportListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public reportListing(requestParameters: ReviewsApiReportListingRequest, options?: RawAxiosRequestConfig) {
        return ReviewsApiFp(this.configuration).reportListing(requestParameters.createReportRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

