/* tslint:disable */
/* eslint-disable */
/**
 * Yoedu Real Estate API
 * API documentation for Yoedu Real Estate backend
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponsePageViewingScheduleResponse } from '../models';
// @ts-ignore
import type { ApiResponseViewingScheduleResponse } from '../models';
// @ts-ignore
import type { CancelViewingScheduleRequest } from '../models';
// @ts-ignore
import type { CreateViewingScheduleRequest } from '../models';
// @ts-ignore
import type { Pageable } from '../models';
/**
 * ViewingSchedulesApi - axios parameter creator
 */
export const ViewingSchedulesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Client hoặc Host/Agent huỷ lịch hẹn kèm lý do (cancel_reason)
         * @summary Huỷ lịch hẹn
         * @param {string} id 
         * @param {CancelViewingScheduleRequest} cancelViewingScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelSchedule: async (id: string, cancelViewingScheduleRequest: CancelViewingScheduleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cancelSchedule', 'id', id)
            // verify required parameter 'cancelViewingScheduleRequest' is not null or undefined
            assertParamExists('cancelSchedule', 'cancelViewingScheduleRequest', cancelViewingScheduleRequest)
            const localVarPath = `/viewing-schedules/{id}/cancel`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelViewingScheduleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Xác nhận lịch hẹn đang ở trạng thái PENDING_CONFIRMATION
         * @summary Xác nhận lịch hẹn
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmSchedule: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('confirmSchedule', 'id', id)
            const localVarPath = `/viewing-schedules/{id}/confirm`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Renter tạo yêu cầu xem nhà cho listing có trạng thái APPROVED
         * @summary Đặt lịch hẹn xem nhà
         * @param {CreateViewingScheduleRequest} createViewingScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSchedule: async (createViewingScheduleRequest: CreateViewingScheduleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createViewingScheduleRequest' is not null or undefined
            assertParamExists('createSchedule', 'createViewingScheduleRequest', createViewingScheduleRequest)
            const localVarPath = `/viewing-schedules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createViewingScheduleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Xem thông tin một lịch hẹn cụ thể — chỉ client hoặc host/agent mới có quyền
         * @summary Lấy chi tiết lịch hẹn
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getById', 'id', id)
            const localVarPath = `/viewing-schedules/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Xem danh sách lịch hẹn của các listing đang được quản lý, lọc theo status tuỳ chọn
         * @summary Lấy lịch hẹn quản lý
         * @param {Pageable} pageable 
         * @param {Array<string>} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getManagedSchedules: async (pageable: Pageable, status?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getManagedSchedules', 'pageable', pageable)
            const localVarPath = `/viewing-schedules/managed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (status) {
                localVarQueryParameter['status'] = status;
            }

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Xem danh sách lịch hẹn đã yêu cầu, lọc theo status tuỳ chọn
         * @summary Lấy lịch hẹn đã yêu cầu
         * @param {Pageable} pageable 
         * @param {Array<string>} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestedSchedules: async (pageable: Pageable, status?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pageable' is not null or undefined
            assertParamExists('getRequestedSchedules', 'pageable', pageable)
            const localVarPath = `/viewing-schedules/requested`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (status) {
                localVarQueryParameter['status'] = status;
            }

            if (pageable !== undefined) {
                for (const [key, value] of Object.entries(pageable)) {
                    localVarQueryParameter[key] = value;
                }
            }

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ViewingSchedulesApi - functional programming interface
 */
export const ViewingSchedulesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ViewingSchedulesApiAxiosParamCreator(configuration)
    return {
        /**
         * Client hoặc Host/Agent huỷ lịch hẹn kèm lý do (cancel_reason)
         * @summary Huỷ lịch hẹn
         * @param {string} id 
         * @param {CancelViewingScheduleRequest} cancelViewingScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelSchedule(id: string, cancelViewingScheduleRequest: CancelViewingScheduleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseViewingScheduleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelSchedule(id, cancelViewingScheduleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ViewingSchedulesApi.cancelSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Xác nhận lịch hẹn đang ở trạng thái PENDING_CONFIRMATION
         * @summary Xác nhận lịch hẹn
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async confirmSchedule(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseViewingScheduleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.confirmSchedule(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ViewingSchedulesApi.confirmSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Renter tạo yêu cầu xem nhà cho listing có trạng thái APPROVED
         * @summary Đặt lịch hẹn xem nhà
         * @param {CreateViewingScheduleRequest} createViewingScheduleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSchedule(createViewingScheduleRequest: CreateViewingScheduleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseViewingScheduleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSchedule(createViewingScheduleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ViewingSchedulesApi.createSchedule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Xem thông tin một lịch hẹn cụ thể — chỉ client hoặc host/agent mới có quyền
         * @summary Lấy chi tiết lịch hẹn
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseViewingScheduleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ViewingSchedulesApi.getById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Xem danh sách lịch hẹn của các listing đang được quản lý, lọc theo status tuỳ chọn
         * @summary Lấy lịch hẹn quản lý
         * @param {Pageable} pageable 
         * @param {Array<string>} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getManagedSchedules(pageable: Pageable, status?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageViewingScheduleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getManagedSchedules(pageable, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ViewingSchedulesApi.getManagedSchedules']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Xem danh sách lịch hẹn đã yêu cầu, lọc theo status tuỳ chọn
         * @summary Lấy lịch hẹn đã yêu cầu
         * @param {Pageable} pageable 
         * @param {Array<string>} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRequestedSchedules(pageable: Pageable, status?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponsePageViewingScheduleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRequestedSchedules(pageable, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ViewingSchedulesApi.getRequestedSchedules']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ViewingSchedulesApi - factory interface
 */
export const ViewingSchedulesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ViewingSchedulesApiFp(configuration)
    return {
        /**
         * Client hoặc Host/Agent huỷ lịch hẹn kèm lý do (cancel_reason)
         * @summary Huỷ lịch hẹn
         * @param {ViewingSchedulesApiCancelScheduleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelSchedule(requestParameters: ViewingSchedulesApiCancelScheduleRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseViewingScheduleResponse> {
            return localVarFp.cancelSchedule(requestParameters.id, requestParameters.cancelViewingScheduleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Xác nhận lịch hẹn đang ở trạng thái PENDING_CONFIRMATION
         * @summary Xác nhận lịch hẹn
         * @param {ViewingSchedulesApiConfirmScheduleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmSchedule(requestParameters: ViewingSchedulesApiConfirmScheduleRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseViewingScheduleResponse> {
            return localVarFp.confirmSchedule(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Renter tạo yêu cầu xem nhà cho listing có trạng thái APPROVED
         * @summary Đặt lịch hẹn xem nhà
         * @param {ViewingSchedulesApiCreateScheduleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSchedule(requestParameters: ViewingSchedulesApiCreateScheduleRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseViewingScheduleResponse> {
            return localVarFp.createSchedule(requestParameters.createViewingScheduleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Xem thông tin một lịch hẹn cụ thể — chỉ client hoặc host/agent mới có quyền
         * @summary Lấy chi tiết lịch hẹn
         * @param {ViewingSchedulesApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById(requestParameters: ViewingSchedulesApiGetByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseViewingScheduleResponse> {
            return localVarFp.getById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Xem danh sách lịch hẹn của các listing đang được quản lý, lọc theo status tuỳ chọn
         * @summary Lấy lịch hẹn quản lý
         * @param {ViewingSchedulesApiGetManagedSchedulesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getManagedSchedules(requestParameters: ViewingSchedulesApiGetManagedSchedulesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageViewingScheduleResponse> {
            return localVarFp.getManagedSchedules(requestParameters.pageable, requestParameters.status, options).then((request) => request(axios, basePath));
        },
        /**
         * Xem danh sách lịch hẹn đã yêu cầu, lọc theo status tuỳ chọn
         * @summary Lấy lịch hẹn đã yêu cầu
         * @param {ViewingSchedulesApiGetRequestedSchedulesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRequestedSchedules(requestParameters: ViewingSchedulesApiGetRequestedSchedulesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageViewingScheduleResponse> {
            return localVarFp.getRequestedSchedules(requestParameters.pageable, requestParameters.status, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ViewingSchedulesApi - interface
 */
export interface ViewingSchedulesApiInterface {
    /**
     * Client hoặc Host/Agent huỷ lịch hẹn kèm lý do (cancel_reason)
     * @summary Huỷ lịch hẹn
     * @param {ViewingSchedulesApiCancelScheduleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelSchedule(requestParameters: ViewingSchedulesApiCancelScheduleRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseViewingScheduleResponse>;

    /**
     * Xác nhận lịch hẹn đang ở trạng thái PENDING_CONFIRMATION
     * @summary Xác nhận lịch hẹn
     * @param {ViewingSchedulesApiConfirmScheduleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    confirmSchedule(requestParameters: ViewingSchedulesApiConfirmScheduleRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseViewingScheduleResponse>;

    /**
     * Renter tạo yêu cầu xem nhà cho listing có trạng thái APPROVED
     * @summary Đặt lịch hẹn xem nhà
     * @param {ViewingSchedulesApiCreateScheduleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createSchedule(requestParameters: ViewingSchedulesApiCreateScheduleRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseViewingScheduleResponse>;

    /**
     * Xem thông tin một lịch hẹn cụ thể — chỉ client hoặc host/agent mới có quyền
     * @summary Lấy chi tiết lịch hẹn
     * @param {ViewingSchedulesApiGetByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getById(requestParameters: ViewingSchedulesApiGetByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseViewingScheduleResponse>;

    /**
     * Xem danh sách lịch hẹn của các listing đang được quản lý, lọc theo status tuỳ chọn
     * @summary Lấy lịch hẹn quản lý
     * @param {ViewingSchedulesApiGetManagedSchedulesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getManagedSchedules(requestParameters: ViewingSchedulesApiGetManagedSchedulesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageViewingScheduleResponse>;

    /**
     * Xem danh sách lịch hẹn đã yêu cầu, lọc theo status tuỳ chọn
     * @summary Lấy lịch hẹn đã yêu cầu
     * @param {ViewingSchedulesApiGetRequestedSchedulesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRequestedSchedules(requestParameters: ViewingSchedulesApiGetRequestedSchedulesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponsePageViewingScheduleResponse>;

}

/**
 * Request parameters for cancelSchedule operation in ViewingSchedulesApi.
 */
export interface ViewingSchedulesApiCancelScheduleRequest {
    readonly id: string

    readonly cancelViewingScheduleRequest: CancelViewingScheduleRequest
}

/**
 * Request parameters for confirmSchedule operation in ViewingSchedulesApi.
 */
export interface ViewingSchedulesApiConfirmScheduleRequest {
    readonly id: string
}

/**
 * Request parameters for createSchedule operation in ViewingSchedulesApi.
 */
export interface ViewingSchedulesApiCreateScheduleRequest {
    readonly createViewingScheduleRequest: CreateViewingScheduleRequest
}

/**
 * Request parameters for getById operation in ViewingSchedulesApi.
 */
export interface ViewingSchedulesApiGetByIdRequest {
    readonly id: string
}

/**
 * Request parameters for getManagedSchedules operation in ViewingSchedulesApi.
 */
export interface ViewingSchedulesApiGetManagedSchedulesRequest {
    readonly pageable: Pageable

    readonly status?: Array<string>
}

/**
 * Request parameters for getRequestedSchedules operation in ViewingSchedulesApi.
 */
export interface ViewingSchedulesApiGetRequestedSchedulesRequest {
    readonly pageable: Pageable

    readonly status?: Array<string>
}

/**
 * ViewingSchedulesApi - object-oriented interface
 */
export class ViewingSchedulesApi extends BaseAPI implements ViewingSchedulesApiInterface {
    /**
     * Client hoặc Host/Agent huỷ lịch hẹn kèm lý do (cancel_reason)
     * @summary Huỷ lịch hẹn
     * @param {ViewingSchedulesApiCancelScheduleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cancelSchedule(requestParameters: ViewingSchedulesApiCancelScheduleRequest, options?: RawAxiosRequestConfig) {
        return ViewingSchedulesApiFp(this.configuration).cancelSchedule(requestParameters.id, requestParameters.cancelViewingScheduleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Xác nhận lịch hẹn đang ở trạng thái PENDING_CONFIRMATION
     * @summary Xác nhận lịch hẹn
     * @param {ViewingSchedulesApiConfirmScheduleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public confirmSchedule(requestParameters: ViewingSchedulesApiConfirmScheduleRequest, options?: RawAxiosRequestConfig) {
        return ViewingSchedulesApiFp(this.configuration).confirmSchedule(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Renter tạo yêu cầu xem nhà cho listing có trạng thái APPROVED
     * @summary Đặt lịch hẹn xem nhà
     * @param {ViewingSchedulesApiCreateScheduleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createSchedule(requestParameters: ViewingSchedulesApiCreateScheduleRequest, options?: RawAxiosRequestConfig) {
        return ViewingSchedulesApiFp(this.configuration).createSchedule(requestParameters.createViewingScheduleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Xem thông tin một lịch hẹn cụ thể — chỉ client hoặc host/agent mới có quyền
     * @summary Lấy chi tiết lịch hẹn
     * @param {ViewingSchedulesApiGetByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getById(requestParameters: ViewingSchedulesApiGetByIdRequest, options?: RawAxiosRequestConfig) {
        return ViewingSchedulesApiFp(this.configuration).getById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Xem danh sách lịch hẹn của các listing đang được quản lý, lọc theo status tuỳ chọn
     * @summary Lấy lịch hẹn quản lý
     * @param {ViewingSchedulesApiGetManagedSchedulesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getManagedSchedules(requestParameters: ViewingSchedulesApiGetManagedSchedulesRequest, options?: RawAxiosRequestConfig) {
        return ViewingSchedulesApiFp(this.configuration).getManagedSchedules(requestParameters.pageable, requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Xem danh sách lịch hẹn đã yêu cầu, lọc theo status tuỳ chọn
     * @summary Lấy lịch hẹn đã yêu cầu
     * @param {ViewingSchedulesApiGetRequestedSchedulesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRequestedSchedules(requestParameters: ViewingSchedulesApiGetRequestedSchedulesRequest, options?: RawAxiosRequestConfig) {
        return ViewingSchedulesApiFp(this.configuration).getRequestedSchedules(requestParameters.pageable, requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }
}

